version: '2'

services:
  app:
    cap_add:
     - NETADMIN
     image: chewnot2chew/boot2root
     command: sh -c "service ufw restart && service vsftpd restart && service ssh restart && tail -f /dev/null"
